Repository Amber-MD/cpptraj, pull requests merged in 2022-01, with the labels that each got.

#929 Fix segfault when reading certain CHAMBER topology files
  src/Parm_Amber.cpp
  src/Version.h
Labels: bugfix

#932 Improve the speed of some post-cluster calculations
  devtools/benchmark/cluster/cluster.sh
  devtools/benchmark/cluster/framelist.sh
  devtools/benchmark/cluster/plot.sh
  doc/cpptraj.lyx
  src/Cluster/Algorithm.cpp
  src/Cluster/Algorithm.h
  src/Cluster/Algorithm_DPeaks.cpp
  src/Cluster/Algorithm_HierAgglo.cpp
  src/Cluster/Algorithm_HierAgglo.h
  src/Cluster/Algorithm_Kmeans.cpp
  src/Cluster/BestReps.cpp
  src/Cluster/BestReps.h
  src/Cluster/CMakeLists.txt
  src/Cluster/Control.cpp
  src/Cluster/Control.h
  src/Cluster/List.cpp
  src/Cluster/List.h
  src/Cluster/Metric_RMS.cpp
  src/Cluster/Node.cpp
  src/Cluster/Node.h
  src/Cluster/Output.cpp
  src/Cluster/Output.h
  src/Cluster/Sieve.cpp
  src/Cluster/Sieve.h
  src/Cluster/Silhouette.cpp
  src/Cluster/Silhouette.h
  src/Cluster/clusterdepend
  src/Cluster/clusterfiles
  src/Frame.cpp
  src/Version.h
  test/Test_Cluster/mysil.frame.dat.save
Labels: enhancement, bugfix

#933 Some 'configure' improvements for OSX
  configure
  get_library.sh
Labels: configure

#934 Fix some pairwise cache behavior in clustering, fix ASCII pairwise cache files
  doc/cpptraj.lyx
  src/Cluster/Cframes.h
  src/Cluster/Control.cpp
  src/Cluster/List.h
  src/Cluster/MetricArray.cpp
  src/Cluster/Sieve.cpp
  src/DataFile.h
  src/DataIO_Std.cpp
  src/DataSet_PairwiseCache.cpp
  src/Version.h
  test/Test_Cluster/RunTest.sh
Labels: enhancement, bugfix

#938 Speed up six-dimensional entropy calculation in GIST
  src/Action_GIST.cpp
  src/Version.h
Labels: enhancement

#939 Faster Hierarchical Agglomerative clustering, output clustering metrics to Data Sets
  README.md
  devtools/benchmark/cluster/cluster.sh
  doc/cpptraj.lyx
  src/Cluster/Algorithm_HierAgglo.cpp
  src/Cluster/CMakeLists.txt
  src/Cluster/Control.cpp
  src/Cluster/Control.h
  src/Cluster/DBI.cpp
  src/Cluster/DBI.h
  src/Cluster/DynamicMatrix.cpp
  src/Cluster/DynamicMatrix.h
  src/Cluster/List.cpp
  src/Cluster/List.h
  src/Cluster/Output.cpp
  src/Cluster/Output.h
  src/Cluster/PseudoF.cpp
  src/Cluster/PseudoF.h
  src/Cluster/clusterdepend
  src/Cluster/clusterfiles
  src/Command.cpp
  src/DataSetList.cpp
  src/DataSetList.h
  src/Exec_CompareClusters.cpp
  src/Exec_CompareClusters.h
  src/RNG.cpp
  src/Version.h
  src/cpptrajdepend
  src/cpptrajfiles
  test/Test_Cluster/RunTest.sh
  test/Test_Cluster/c1.cmetrics.dat.save
Labels: enhancement, bugfix
